name: ngdart
description: A command-line tool for creating and managing AngularDart projects.
version: 1.0.3
homepage: https://github.com/angulardart-community/ngdart
repository: https://github.com/angulardart-community/ngdart
executables:
  ngdart:

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies: 
  ansicolor: ^2.0.1
  args: ^2.1.1
  build: ^2.0.3
  cli_util: ^0.3.3
  glob: ^2.0.1
  interact: ^2.0.0
  path: ^1.8.0
  webdev: ^2.7.4

dev_dependencies:
  build_config: ^0.4.7
  build_runner: ^1.12.2
  build_version: ^2.0.2
  test: ^1.16.5

# dev_dependencies: 
#   build_config: ^0.4.7
#   build_runner: ^1.12.1
#   build_version: ^2.0.2
#   test: ^1.17.9