name: ngdart
description: A command-line tool for creating and managing AngularDart projects.
version: 1.0.2
homepage: https://github.com/angulardart-community/ngdart
repository: https://github.com/angulardart-community/ngdart
executables:
  ngdart:

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies: 
  ansicolor: ^2.0.1
  args: ^2.1.1
  build: ^2.0.3
  cli_util: ^0.3.3
  path: ^1.8.0
dev_dependencies: 
  build_config: ^1.0.0
  build_runner: ^2.0.6
  build_version: ^2.0.3
  test: ^1.17.9